name: Infinity Bot CRON

on:
  schedule:
    - cron: '*/5 * * * *' # รันทุก 5 นาที
  workflow_dispatch:      # ปุ่มกดรันเอง

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install ccxt pandas ta gspread oauth2client requests
      - name: Run Bot
        env:
          GDRIVE_API_CREDENTIALS: ${{ secrets.GDRIVE_API_CREDENTIALS }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}  # 👈 ต้องเพิ่มบรรทัดนี้!
        run: python main.py
